name: 🚀 Deploy Website on Push

on:
  push:
    branches:
      - main  # Only deploy on push to the main branch

jobs:
  web-deploy:
    name: 🎉 Build and Deploy React App
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code from the repository
    - name: 🚚 Checkout code
      uses: actions/checkout@v4  # Checkout the latest code from the main branch

    # Step 2: Set up Node.js (use the version of Node you require)
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.18.0'  # You can change this to the version of Node.js your app needs

    # Step 3: Install dependencies using npm (or yarn if you prefer)
    - name: Install dependencies
      run: npm install

    # Step 4: Build the React app (this will generate a 'build/' directory)
    - name: Build React app
      run: npm run build  # Assumes you have a build script defined in your package.json

    # Step 5: Sync build output (the 'build/' directory) to the FTP server
    - name: 📂 Sync files to FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.gruene-weltweit.de  # FTP server URL
        username: deploygrueneweltweit  # FTP username
        password: ${{ secrets.FTP_PASSWORD }}  # Using a secret for security
        local-dir: ./build  # The directory created by `npm run build` (default is 'build/')
        remote-dir: /  # Deploy to the root folder of the server

    # Optional: Add notifications or clean-up steps as necessary
